Fixed external funds calculation (#111)
* Fixed the horizon graph when external funds are desposited, and fixed external funds to users where broken too (backend was inverted

* Added a unit test to validate external funds are considered in the backend

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -5,6 +5,7 @@ fail() { echo "$1"; exit 1; }
 
 echo "Running formatter on staged files"
 (cd frontend && npm run format:staged) || fail "Fronted failed to auto-format staged files"
+(cd backend && cargo fmt) || fail "Backend failed to auto-format staged files"
 
 echo "Running pre-commit checks..."
 
