Used lint-staged in both backend and frontend and moved this dependency to the root of this package (#114)

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -3,16 +3,13 @@ set -euo pipefail
 
 fail() { echo "$1"; exit 1; }
 
-echo "Running formatter on staged files"
-(cd frontend && npm run format:staged) || fail "Fronted failed to auto-format staged files"
-(cd backend && cargo fmt) || fail "Backend failed to auto-format staged files"
+echo "Running formatter on staged files..."
+npm run format:staged || fail "Failed to auto-format staged files"
 
 echo "Running pre-commit checks..."
-
 (cd backend && cargo fmt --check) || fail "Backend formatting failed!"
 (cd backend && cargo clippy -- -D warnings) || fail "Backend clippy failed!"
 (cd frontend && npm run check) || fail "Frontend type checking failed!"
-(cd frontend && npm run format:check) || fail "Frontend lint failed!"
 (cd backend && cargo test) || fail "Backend tests failed!"
 (cd frontend && npm test) || fail "Frontend tests failed!"
 
